# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37bec2022db894fd181ec9606613694f1366d760614e71bf6f9418a0671d2bc2ace80f814f2590759215cf99f1247bfadf130c7a9c76585a0251174933d46ac4

test:
  secret_key_base: 0b5671f2764382b3bb029ed92beb5fdaefce9a0452f76ce8e3b50d5f0300d16eb00578b91c76b7106a88d5c4452124759b31c5c2a04a669afd23637dbdad0255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
